interactions:
  user_id_column: "userId"
  item_id_column: "movieId"
  rating_column: "rating"
  timestamp_column: "timestamp"
  
  implicit:
    min_rating: 4.0
    
  split:
    test_size_ratio: 0.1
    val_size_ratio: 0.1
    
  output:
    train_path: "data/processed/train_interactions.parquet"
    valid_path: "data/processed/valid_interactions.parquet"
    test_path: "data/processed/test_interactions.parquet"
